#!/bin/bash
UNIT=""
while [ "$1" != "" ]; do
	if [ "$1" == "-a" ]; then
		# Run all tests
		export UNITTEST_RUN_ALL="1"
	elif [ "$1" == "-d" ]; then
		# Show durations
		ARGS="${ARGS} --durations 0"
	else
		UNIT="${UNIT} digtick.tests.${1}"
	fi
	shift	
done
if [ "$UNIT" == "" ]; then
	UNIT="digtick.tests"
fi
python3 -m unittest ${ARGS} ${UNIT}
