#!/bin/bash -ev
#
#

DID_FAIL="0"
must_fail() {
	DID_FAIL="1"
}

assert_failed() {
	if [ "$DID_FAIL" == "0" ]; then
		echo "Previous command should have failed, but DID NOT."
		exit 1
	fi
	DID_FAIL="0"
}

# Run example commands through coverage
cov="coverage run -a --source digtick --omit=tpg.py,PrefixMatcher.py,RandomDist.py,TableFormatter.py,MultiCommand.py,FriendlyArgumentParser.py -m"
digtick="$cov digtick.__main__"

# Run some tests that are in modules __main__
$cov digtick.ExpressionParser

$digtick parse "A B C"
$digtick parse -n "A B C"
$digtick parse -f text "A B C"
for format in text pretty-text tex-tech tex-math dot internal; do
	$digtick parse -f $format "A B C ^ B A C (!A !B !C) (!(A B C)) @ D % E + 1"
done
(
	echo "A B C"
	echo "B C A"
	echo "# test that comment works"
	echo "A !B C"
) | $digtick parse -F -e -

$digtick make-table 'A B C' '!B !C' >/tmp/table1
for format in text pretty tex compact logisim; do
	cat /tmp/table1 | $digtick print-table -f $format
done
$digtick print-table -L examples/logisim_full_adder.txt

$digtick make-table 'A B + !B C' >/tmp/table2
$digtick make-table 'A B + !B C + A !B !C' >/tmp/table3
$digtick diff-table /tmp/table2 /tmp/table3
echo ':A,B,C:Z:5404' | $digtick diff /tmp/table2 || must_fail; assert_failed
echo ':A,D,C:Y:5404' | $digtick diff /tmp/table2 || must_fail; assert_failed

$digtick kv /tmp/table1
$digtick kv -o P /tmp/table1 || must_fail; assert_failed
$digtick kv -r /tmp/table1
$digtick kv -x 1 -y 2 -X -Y -d BCA /tmp/table1
$digtick kv -x 1 -y 2 -X -Y -d C,B,A /tmp/table1
cat /tmp/table1 | head -n -1 | $digtick kv -x 1 -y 2 -X -Y -d BCA || must_fail; assert_failed
cat /tmp/table1 | head -n -1 | $digtick kv -x 1 -y 2 -X -Y -d BCA --unused-value-is '*'
$digtick kv -x 1 -y 2 -X -Y -d BCAA /tmp/table1 || must_fail; assert_failed
$digtick kv -x 1 -y 2 -X -Y -d BCAX /tmp/table1 || must_fail; assert_failed
$digtick kv -x 1 -y 2 -X -Y -d BCA -O /tmp/kv.svg /tmp/table1

$digtick synth /tmp/table1
$digtick synth /tmp/table1 --show-all-solutions

$digtick sat /tmp/table1 'A B' || must_fail; assert_failed
$digtick sat /tmp/table1 'A B C'

$digtick eq 'A B C' 'A B !C' || must_fail; assert_failed
$digtick eq 'A(B C)' 'B(A C)'

$digtick random-expr 4 10
$digtick random-expr --allow-nand-nor-xor 4 10
$digtick random-table 4
$digtick random-table -1 100 -0 0 4
$digtick random-table -1 100 -0 0 -o Z 4
$digtick random-table -1 100 -0 50 4 || must_fail; assert_failed

$digtick transform -t simplify 'A C B'
$digtick transform -t nand 'A ^ B'
$digtick transform -t nor 'A ^ B'
$digtick transform -t nand -t nor -t nand 'A ^ B'
$digtick transform -t simplify '(A + 1)(B & 0)((1))'
$digtick transform -t simplify '(A + 1)(B & 0)((1)) + (!B !C !A) + (A + A) + (A A) + (X @ 1 @ 1)'
$digtick transform -t simplify '-((A + 1)(B & 0)((1)) + (!B !C !A) + (A + A) + (A A) + (-X @ 1 @ 1))(C 1)(D + 0)((X)+(X))((Y)(Y))(Z % 0 % 0)(K + !K)'

for dev in sr-nand-ff d-ff jk-ff jk-ms-ff; do
	$digtick dtd-create --random-seed 12345 -d $dev
	$digtick dtd-create --random-seed 23456 -n -d $dev
done
$digtick dtd-create -i >/tmp/dtd
$digtick dtd-create --random-seed blubb -d jk-ff "J=00001111000011110000111100001111"
$digtick dtd-create --random-seed blubb -d jk-ff "J=000011110000111100001111000" || must_fail; assert_failed

rm -f /tmp/dtd.svg
$digtick dtd-render -o /tmp/dtd.svg /tmp/dtd
$digtick dtd-render -o /tmp/dtd.svg /tmp/dtd || must_fail; assert_failed
$digtick dtd-render -o /tmp/dtd.svg -f /tmp/dtd

$digtick sim-combinatorial src/digtick/tests/data/awful.circ >/tmp/awful.txt

$digtick sim-sequential -s FF1,FF2,FF3,FF4 src/digtick/tests/data/stateful.circ >/tmp/state_table.txt
$digtick sim-sequential -s B4,B3,B2,B1,B0 -n main_gates examples/counter_5bit.circ >/tmp/state_table2.txt

$digtick analyze-sequential -vv /tmp/state_table.txt
$digtick analyze-sequential -vv /tmp/state_table2.txt
$digtick analyze-sequential -f dot /tmp/state_table.txt
$digtick analyze-sequential -f json /tmp/state_table.txt
echo ":FF1,FF2,FF3,FF4,FF5:FF1',FF2',FF3',FF4',FF5':5555000055550000,5555000000005555,4455440044554400,55005500550055,4051514040515140" | $digtick analyze-sequential
echo ":FF1,FF2,FF3,FF4,FF5:FF1',FF2',FF3',FF4',FF5':5555000055550000,5555000000005555,4455440044554400,55005500550055,4051514040515140" | $digtick analyze-sequential -f dot
$digtick analyze-sequential /tmp/table1 || must_fail; assert_failed

$digtick mutate -m G src/digtick/tests/data/invgate.circ
$digtick mutate -m G:c=AND src/digtick/tests/data/invgate.circ
$digtick mutate -m G:c=AND,c=OR src/digtick/tests/data/invgate.circ
$digtick mutate -m G:inv=foo src/digtick/tests/data/invgate.circ || must_fail; assert_failed
$digtick mutate -m G:comb=foo src/digtick/tests/data/invgate.circ || must_fail; assert_failed
$digtick mutate -m G:randcomb=foo src/digtick/tests/data/invgate.circ || must_fail; assert_failed
$digtick mutate -m G:foo=bar src/digtick/tests/data/invgate.circ || must_fail; assert_failed
$digtick mutate -m G:comb=999 src/digtick/tests/data/invgate.circ || must_fail; assert_failed
$digtick mutate -m G:inv=1 src/digtick/tests/data/invgate.circ
$digtick mutate -m G:inv=1,randcomb=3 src/digtick/tests/data/invgate.circ
$digtick mutate -m G:inv=1,comb=1,comb=2 --prefix foobar src/digtick/tests/data/invgate.circ
