#!/bin/bash -e
#
#

DID_FAIL="0"
must_fail() {
	DID_FAIL="1"
}

assert_failed() {
	if [ "$DID_FAIL" == "0" ]; then
		echo "Previous command should have failed, but DID NOT."
		exit 1
	fi
	DID_FAIL="0"
}

# Run example commands through coverage
digtick="coverage run -a --source digtick --omit=tpg.py,PrefixMatcher.py,RandomDist.py,TableFormatter.py,MultiCommand.py,FriendlyArgumentParser.py -m digtick.__main__"

$digtick parse "A B C"
$digtick parse -n "A B C"
$digtick parse -f text "A B C"
for format in text pretty-text tex-tech tex-math dot internal; do
	$digtick parse -f $format "A B C ^ B A C (!A !B !C) (!(A B C)) @ D % E + 1"
done
(
	echo "A B C"
	echo "B C A"
	echo "# test that comment works"
	echo "A !B C"
) | $digtick parse -F -e -

$digtick make-table 'A B C' '!B !C' >/tmp/table1
for format in text pretty tex compact logisim; do
	cat /tmp/table1 | $digtick print-table -f $format
done

$digtick make-table 'A B + !B C' >/tmp/table2
$digtick make-table 'A B + !B C + A !B !C' >/tmp/table3
$digtick diff-table /tmp/table2 /tmp/table3
echo ':A,B,C:Z:5404' | $digtick diff /tmp/table2 || must_fail; assert_failed
echo ':A,D,C:Y:5404' | $digtick diff /tmp/table2 || must_fail; assert_failed

$digtick kv /tmp/table1
$digtick kv -r /tmp/table1
$digtick kv -x 1 -y 2 -X -Y -d BCA /tmp/table1
cat /tmp/table1 | head -n -1 | $digtick kv -x 1 -y 2 -X -Y -d BCA || must_fail; assert_failed
cat /tmp/table1 | head -n -1 | $digtick kv -x 1 -y 2 -X -Y -d BCA --unused-value-is '*'

$digtick synth /tmp/table1 --show-all-solutions

$digtick sat /tmp/table1 'A B' || must_fail; assert_failed
$digtick sat /tmp/table1 'A B C'
