#!/bin/bash
#
#

cat <<EOF
#let bnand = box(width: 1em, height: 0.6em)[#place(center, dy: -0.1em)[#sym.and] #place(center, dy: -0.1em)[#text(size: 0.85em)[#sym.tilde]]]
#let bnor = box(width: 1em, height: 0.6em)[#place(center, dy: -0.1em)[#sym.or] #place(center, dy: -0.1em)[#text(size: 0.85em)[#sym.tilde]]]
#let bnot(body) = \$overline(#v(1em)#h(0em) body)$
EOF

while read formula; do
	TEXT=$(digtick parse -f text "${formula}")
	TYPST_TECH=$(digtick parse -f typst "${formula}")
	TYPST_MATH1=$(digtick parse -f typst -F math-operators "${formula}")
	TYPST_MATH2=$(digtick parse -f typst -F math-operators -F math-constants "${formula}")
	
	echo '```'
	echo "$formula"
	echo "$TEXT"
	echo '```'
	echo  "\$ ${TYPST_TECH} \$"
	echo  "\$ ${TYPST_MATH1} \$"
	echo  "\$ ${TYPST_MATH2} \$"
done <<EOF
A B
A !B !C + B C
A (B + C)
(A + B) C
A C (B + D) + E + F
A C !(B + D) + E + !F
A C !(B + !(D + !E)) + E + !F
A B !C D !E F !G !H !I !J
A @ B % C
A B C + !A !B !C + (!1 + !0) @ Z % W
EOF
