#!/bin/bash
#
#

cat <<EOF
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\begin{document}
EOF

while read formula; do
	TEXT=$(digtick parse -f text "${formula}")
	TEX_TECH=$(digtick parse -f tex "${formula}")
	TEX_MATH1=$(digtick parse -f tex -F math-operators "${formula}")
	TEX_MATH2=$(digtick parse -f tex -F math-operators -F math-constants "${formula}")
	
	echo "\\begin{verbatim} $formula \\end{verbatim}"
	echo "\\begin{verbatim} $TEXT \\end{verbatim}"
	echo  "\[ ${TEX_TECH} \]"
	echo  "\[ ${TEX_MATH1} \]"
	echo  "\[ ${TEX_MATH2} \]"
done <<EOF
A B
A !B !C + B C
A (B + C)
(A + B) C
A C (B + D) + E + F
A C !(B + D) + E + !F
A C !(B + !(D + !E)) + E + !F
A B !C D !E F !G !H !I !J
A @ B % C
A B C + !A !B !C + (!1 + !0) @ Z % W
EOF

cat <<EOF
\end{document}
EOF
