name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Python environment
        run: pip3 install coverage .

      - name: Run all testcases and view code coverage
        run: |
          UNITTEST_RUN_ALL="1" coverage run -m unittest digtick.tests
          coverage xml
