name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install build and runtime dependencies
        run: |
          sudo apt-get install graphviz
          pip3 install coverage pylint
          git clone --depth 1 https://github.com/johndoe31415/jbin

      - name: Install digtick in venv and test to make sure it works as system package
        run: |
          pip3 install .
          UNITTEST_RUN_ALL="1" python3 -m unittest digtick.tests

      # When measuring coverage and the package is installed as system package,
      # the absolute paths show up in the coverage report. This is ugly.
      # Install editable so we get paths as expected for coverage measurement.
      # Also for linting, the suppressions refer to relative paths and
      # false-positives will show up when not in editable mode.
      - name: Reinstall digtick as editable package
        run: pip3 install -e .

      - name: Lint code, fail if there are linter errors
        run: jbin/tpp --lint-code

      - name: Verify that all README.md commands work
        run: scripts/run_all_readme_commands

      - name: Run testcases and determine coverage
        run: jbin/tpp --coverage-scripts --report-xml --set-test-environment

      - name: Show debug output
        run: ls -la

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
