name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Python environment
        run: pip3 install coverage .

      - name: Run testcases and determine coverage
        run: |
          UNITTEST_RUN_ALL="1" coverage run --source digtick --omit "tpg.py,PrefixMatcher.py,RandomDist.py,TableFormatter.py,MultiCommand.py" -m unittest digtick.tests
          coverage xml

      - name: Determine coverage for the CLI tools
        run: scripts/command_line_coverage

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          format: cobertura
          file: coverage.xml
